### ISSUE TITLE
A question about Input type and b7

### ISSUE THREAD

**Issue by sadransh** [naviocean/vovnet_sku110#1]
Thank you for sharing your work. 

I have a question on the type of input [here](https://github.com/naviocean/faster_rcnn_sku110/blob/6b2e04f5b9e5eeb6fe68ad5571c1b4115897560f/projects/sku110/backbones/efficientnet.py#L614) you have commented #rgb. 
Does this mean just 3 channels or it means the type of input images should be RGB and not BGR? 

Another question about pre-trained weights for efficient net-B7 is there any? or any way to convert them for detectron2? 

Thanks a lot.

**Comment by naviocean** [comment]
@sadransh it's total channels of input images, default is 3 for both RGB or BGR :)
Here is pretrained model for B7 `https://www.dropbox.com/s/izsry10l92otav3/efficientnet-b7-e5c62608.pth?dl=1`

**Comment by sadransh** [comment]
So, the input is the default detectron2 input and it is BGR. 

Thanks a lot.

**Comment by sadransh** [comment]
Another question, Do you have any comparison on APs for different efficient nets b0~b7 ? on your dataset?
